language: go

go:
- 1.14.x

jobs:
  include:
  - stage: test
    install:
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/mattn/goveralls
    script:
    - go test -v -covermode=atomic -coverprofile=cover.out ./...
    - "${HOME}/gopath/bin/goveralls -coverprofile=cover.out -repotoken ${COVERALLS_TOKEN}"

env:
  global:
    secure: pg5opFg429aR/mVsC/JmRjeszENx4XtYUhb9pF+fXxIOoRLrLHJze7egjJX4YDd7nlbCzVbAoW/P2aFOKs8ca7yav0hJoF5uTAaOgnyOAbkQcyvgv8ZRK78KKF1cSLfFFU58ziRzmgqp23HhBaNjzbjZi5XU1TIxjugt4aCgLTAfKliLjW5+vbmumpdfps8k2+gGAGkVYc6KotKrFKdH6/Ce+7O/4+tgxu+Nzi/lN6c1J+OXWsqWabiLQ4GRSLqtw8utOn9Z1uHqyj8FMNbJLPGNpkydXx3yEPOp8+TlL1+C26GN+IJ6UaoCKhevHMy1L+egXmfJJQRg/uMZG2VDQwM1X3JVUDX6xx4BXlw/cqcxGfU7qQjGgIL3hnlEQz6nHEZmGiC1lNLJqG0+5tu50K13//yDHKYa02BVaySopMVkxJR1I1qWFaKki8dwXvZCUhdiIFXcZIf8aVcrAEYxpM0GQQ7CDQpkU8S7vHn+NPJqDF5rxJkk5d21QBD6guPdthQaUHG7RenGv1Sm/QmJ93GSnTf80hcd1byAJJb3lTuhI1LdSMBJi2jn07F3a3zdo5visNoghQ3zaXXT1jSnhUJPbg99EbILzo0/H8StekGoNlAGLBxPZD5uHj8el8OnncTUSA6jI6BL+3wJI4pgj5egbewHjowM3Zf4dgp/QOQ=
